Name: [[NAME]]
Settings:
  Port: [[PORT]]
  Type: [[TYPE]]
  Template:
    Resources:
      [[NAME]]Hosting:
        Type: AWS::Amplify::App
        Properties:
          Name: [[NAME]]
          BuildSpec: |
            version: 1
            frontend:
              phases:
                preBuild:
                  commands:
                    - yarn
                build:
                  commands:
                    - yarn generate
              artifacts:
                baseDirectory: dist
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
