name: Create release from tags

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Packages
        run: make VERSION=${{ github.ref_name }} package
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload win-x64 release
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.packages/dc-${{ github.ref_name }}-win-x64.zip
          asset_name: dc-${{ github.ref_name }}-win-x64.zip
          asset_content_type: application/zip
      - name: Upload linux-x64 release
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.packages/dc-${{ github.ref_name }}-linux-x64.zip
          asset_name: dc-${{ github.ref_name }}-linux-x64.zip
          asset_content_type: application/zip