name: Tag new releases
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag release
        id: tag_release
        uses: butlerlogic/action-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          tag_prefix: "v"
          root: "/src/DC.AWS.Projects.Cli/DC.AWS.Projects.Cli.csproj"
          regex_pattern: "<Version>([0-9\\.]{5}([-\\+][\\w\\.0-9]+)?)</Version>"
      - name: Test
        run: echo ${{ steps.tag_release.outputs.tagcreated }}