name: Tag new releases
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag release
        id: tag_release
        uses: butlerlogic/action-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          tag_prefix: "v"
          root: "src/DC.AWS.Projects.Cli/DC.AWS.Projects.Cli.csproj"
          regex_pattern: "<Version>([0-9\\.]{5}([-\\+][\\w\\.0-9]+)?)</Version>"
      - name: Build Packages
        if: steps.tag_release.outputs.tagname
        run: make VERSION=${{ steps.tag_release.outputs.tagname }} package
      - name: Create Release
        if: steps.tag_release.outputs.tagname
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_release.outputs.tagname }}
          release_name: Release ${{ steps.tag_release.outputs.tagname }}
          body: Release ${{ steps.tag_release.outputs.tagname }}
          draft: false
          prerelease: false
      - name: Upload win-x64 release
        if: steps.tag_release.outputs.tagname
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.packages/dc-aws-${{ steps.tag_release.outputs.tagname }}-win-x64.zip
          asset_name: dc-aws-${{ steps.tag_release.outputs.tagname }}-win-x64.zip
          asset_content_type: application/zip
      - name: Upload linux-x64 release
        if: steps.tag_release.outputs.tagname
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.packages/dc-aws-${{ steps.tag_release.outputs.tagname }}-linux-x64.zip
          asset_name: dc-aws-${{ steps.tag_release.outputs.tagname }}-linux-x64.zip
          asset_content_type: application/zip