name: Tag new releases
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag release
        id: tag_release
        uses: butlerlogic/action-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          tag_prefix: "v"
          version: "0.13.0"
      - name: Test
        run: echo ${{ steps.tag_release.outputs.tagcreated }}